import { resolve } from 'path';
import react from '@vitejs/plugin-react';
import { defineConfig } from 'vitest/config';

export default defineConfig({
    plugins: [react()],
    resolve: {
        alias: [
            // @/routes is generated by the Wayfinder Vite plugin at build time
            // and is excluded from version control. Alias it to a lightweight
            // stub so tests can import pages that reference route helpers without
            // requiring a full Vite build. Individual test files can still
            // override specific exports via vi.mock('@/routes', ...).
            // Must be listed before the '@' catch-all alias so it matches first.
            {
                find: '@/routes',
                replacement: resolve(__dirname, 'resources/js/tests/__stubs__/routes.ts'),
            },
            { find: '@', replacement: resolve(__dirname, 'resources/js') },
            { find: '@flowki/shared', replacement: resolve(__dirname, 'shared/src') },
        ],
    },
    test: {
        environment: 'jsdom',
        globals: true,
        setupFiles: ['resources/js/tests/setup.ts'],
        include: ['resources/js/tests/**/*.{test,spec}.{ts,tsx}'],
    },
});
