import { resolve } from 'path';
import react from '@vitejs/plugin-react';
import type { Plugin } from 'vite';
import { defineConfig } from 'vitest/config';

/**
 * Vite plugin that provides virtual stub modules for every
 * `@/actions/**` import.
 *
 * The real action files are generated by the Wayfinder Vite plugin at build
 * time and excluded from version control.  In the test environment each
 * `@/actions/Foo/Bar` path is mapped to a UNIQUE virtual module so that
 * individual `vi.mock('@/actions/...', () => ({...}))` calls in test files
 * target the correct module and do not clobber each other.
 */
function actionsStubPlugin(): Plugin {
    const ACTIONS_STUB = resolve(__dirname, 'resources/js/tests/__stubs__/actions.ts');
    const ROUTES_STUB = resolve(__dirname, 'resources/js/tests/__stubs__/routes.ts');
    const ROUTES_SUB_STUB = resolve(__dirname, 'resources/js/tests/__stubs__/routes-sub.ts');
    // After @/… alias expansion by Vite's built-in alias plugin:
    const RESOLVED_ACTIONS_DIR = resolve(__dirname, 'resources/js/actions');
    const RESOLVED_ROUTES = resolve(__dirname, 'resources/js/routes');

    return {
        name: 'vitest-actions-stub',
        enforce: 'pre',
        resolveId(id: string) {
            // ── Pre-alias paths ──────────────────────────────────────────────
            if (id === '@/routes') {
                return ROUTES_STUB;
            }

            if (id.startsWith('@/routes/')) {
                return `${ROUTES_SUB_STUB}?routeId=${encodeURIComponent(id)}`;
            }

            if (id.startsWith('@/actions/')) {
                return `${ACTIONS_STUB}?actionId=${encodeURIComponent(id)}`;
            }

            // ── Post-alias paths (Vite's @→resources/js alias ran first) ─────
            if (id === RESOLVED_ROUTES || id === RESOLVED_ROUTES + '.ts') {
                return ROUTES_STUB;
            }

            if (id.startsWith(RESOLVED_ROUTES + '/')) {
                return `${ROUTES_SUB_STUB}?routeId=${encodeURIComponent(id)}`;
            }

            if (id.startsWith(RESOLVED_ACTIONS_DIR + '/') || id.startsWith(RESOLVED_ACTIONS_DIR + '\\')) {
                return `${ACTIONS_STUB}?actionId=${encodeURIComponent(id)}`;
            }
        },
    };
}

export default defineConfig({
    plugins: [react(), actionsStubPlugin()],
    resolve: {
        alias: [
            { find: '@', replacement: resolve(__dirname, 'resources/js') },
            { find: '@flowki/shared', replacement: resolve(__dirname, 'shared/src') },
        ],
    },
    test: {
        environment: 'jsdom',
        globals: true,
        setupFiles: ['resources/js/tests/setup.ts'],
        include: ['resources/js/tests/**/*.{test,spec}.{ts,tsx}'],
    },
});
