/**
 * Generic stub for Wayfinder-generated action controller modules.
 *
 * The real action files (resources/js/actions/**) are generated by the
 * `@laravel/vite-plugin-wayfinder` Vite plugin and are excluded from version
 * control (/resources/js/actions in .gitignore).
 *
 * In vitest.config.ts, a custom `actionsStubPlugin()` intercepts `@/actions/*`
 * imports in `resolveId()` and redirects them to this stub through a virtual
 * module query string so Vite can resolve a concrete module during tests.
 * Individual test files can still override specific named exports via:
 *   vi.mock('@/actions/App/Http/Controllers/FooController', () => ({ ... }))
 * which Vitest hoists before modules are evaluated, taking precedence over
 * this stub at runtime.
 *
 * All exported functions return a URL descriptor object compatible with
 * Inertia's router helpers so that code that calls the action stub without
 * a vi.mock override won't throw at runtime.
 */

type ActionFn = (...args: unknown[]) => { url: string };

const stub: ActionFn = () => ({ url: '/' });

/* Standard CRUD */
export const index = stub;
export const store = stub;
export const show = stub;
export const update = stub;
export const destroy = stub;

/* Common aliases used by controllers */
export const complete = stub;
export const move = stub;
export const reorder = stub;
export const create = stub;
export const join = stub;
export const joinStore = stub;
export const upload = stub;
export const toggle = stub;
export const chat = stub;
export const recent = stub;
export const confirm = stub;

/* Notification-specific */
export const markRead = stub;
export const markAllRead = stub;

/* Settings */
export const edit = stub;
