/**
 * Stub for the Wayfinder-generated @/routes module.
 *
 * The real routes file is generated by the `@laravel/vite-plugin-wayfinder`
 * Vite plugin at build time and is excluded from version control
 * (/resources/js/routes in .gitignore). This stub is used by Vitest so that
 * component tests can import pages that reference route helpers without
 * requiring a full Vite build.
 *
 * Individual test files override specific routes via `vi.mock('@/routes', ...)`.
 */

const route = (path: string) => () => path;

export const login = route('/login');
export const register = route('/register');
export const logout = route('/logout');
export const dashboard = route('/dashboard');
export const privacy = route('/privacy');
export const terms = route('/terms');
export const appearance = route('/settings/appearance');
export const home = route('/');
