/**
 * Generic stub for Wayfinder-generated route sub-path modules:
 *   @/routes/password
 *   @/routes/profile
 *   @/routes/social
 *   @/routes/verification
 *
 * The real files are generated by the Wayfinder plugin and excluded from
 * version control. The vitest.config.ts plugin maps every `@/routes/*`
 * import to this stub (with a unique query string per path so vi.mock()
 * calls target independent module instances). Individual tests can still
 * override specific exports via vi.mock('@/routes/password', ...).
 */

type RouteFn = (...args: unknown[]) => string;

const stub: RouteFn = () => '/';

// password routes (used by ForgotPassword, ResetPassword pages)
export const request = stub;
export const store = stub;
export const reset = stub;

// profile routes (used by Settings Profile pages)
export const edit = stub;
export const update = stub;

// social auth routes (used by SocialAuthButtons)
export const link = stub;
export const unlink = stub;
export const redirect = stub;
export const callback = stub;

// verification routes (used by VerifyEmail page)
export const send = stub;
export const verify = stub;
