project_id             = "flowki-490210"
region                 = "australia-southeast1"
app_name               = "flowki"
app_url                = "https://flowki.family"
terraform_state_bucket = "414442590715-tfstate"
github_org             = "S8-Digital"
github_repo            = "flowki"