server {
    listen [::]:8080;
    listen 8080;

    server_name _;

    root /var/www/public;
    index index.php;

    access_log /dev/stdout main_timed;
    error_log /dev/stderr notice;

    client_max_body_size 32M;

    # Force HTTPS
    # if ($http_x_forwarded_proto != "https") {
    #     return 301 https://$host$request_uri;
    # }

    # Redirect all other HTTP to HTTPS if certificates exist
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ ^/index.php {
        try_files $uri =404;
        fastcgi_pass 127.0.0.1:9000; # Assuming PHP-FPM is listening on 9000
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;

        fastcgi_param HTTP_X_FORWARDED_PROTO https;
        fastcgi_param HTTPS on; # Tell PHP-FPM/Laravel it's HTTPS

        fastcgi_param HTTP_X_FORWARDED_PORT 443; # Explicitly set to 443 as the original port

        fastcgi_buffers 8 64k;
        fastcgi_buffer_size 64k;
        fastcgi_busy_buffers_size 128k;
        fastcgi_connect_timeout 60;
        fastcgi_send_timeout 300;
        fastcgi_read_timeout 300;
    }

    location ~* \.(jpg|jpeg|gif|png|css|js|ico|xml)$ {
        expires 5d;
        log_not_found off; # Often good to prevent excessive log noise for static assets
    }

    location ~ /\. {
        log_not_found off;
        deny all;
    }

    location ~ ^/(fpm-status|fpm-ping)$ {
        access_log off;
        allow 127.0.0.1;
        deny all;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
    }
}